[workspace]
members = ["crates/hs-core", "crates/hs-cli"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.95"
license = "MIT"

[workspace.dependencies]
borsh = { version = "1.8.1", default-features = false, features = ["std", "derive"] }
sha2 = { version = "0.10.9", default-features = false, features = ["force-soft"] }

[profile.release]
lto = "thin"
codegen-units = 1
overflow-checks = true

[profile.dev]
overflow-checks = true
