[package]
name = "hs-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "hachistep"
path = "src/main.rs"

[dependencies]
hs-core = { path = "../hs-core" }
sha2.workspace = true
clap = { version = "4.6", default-features = false, features = ["std", "derive", "help", "usage", "error-context"] }
serde_json = { version = "1.0.151", features = ["arbitrary_precision"] }

[features]
default = []
trace = ["hs-core/trace"]
